minsu-steven-kim/cra5-ssd

- shell_pkg/shell.py
- shell_pkg/test_shell.py
Test Shell write함수에서 입력되는 파라미터와 패키지 파일을 검증하는 코드 입니다!
> Shell Write 구현(검증 중심)

- virtual_ssd_pkg/test_virtual_ssd.py
- virtual_ssd_pkg/virtual_ssd.py
명령어
1) ssd R [LBA]
2) ssd W [LBA] [value]
* LBA : 0~99 사이의 10진수
* 값 0x로 시작하는 10자리 글자 
해당 두 명령어에 대해서 parsing 하고 validation 검증
잘못된 값이 들어왔을 경우 ValueError raise
> ssd command parsing/validation

- shell_pkg/shell.py
- shell_pkg/test_shell.py
Shell의 Write 기능 개발
- virtual_ssd.py 실행을 위한 command line 생성 및 python 실행 함수 추가
- 관련 유닛 테스트 코드 추가
> Shell Write 명령 실행 구현

- virtual_ssd_pkg/ssd.py
- virtual_ssd_pkg/test_virtual_ssd.py
W command 시 16진수 확인하는 부분 추가하였습니다.
> [feature] command value 16진수 확인

- virtual_ssd_pkg/ssd.py
- virtual_ssd_pkg/test_virtual_ssd.py
> Virtual SSD Write 구현 PR

- shell_pkg/command.py
- shell_pkg/test_shell.py
미반영된 commit 및 conflict 처리 코드 적용
> [conflict] merge 미반영 코드 적용

- virtual_ssd_pkg/command.py
- virtual_ssd_pkg/ssd.py
- virtual_ssd_pkg/test_command.py
- virtual_ssd_pkg/test_virtual_ssd.py
기존 VirtualSSD 클래스 내의 Read 함수 구현 부를 ReadCommand 클래스의 execute 함수로 이동하였습니다.
이에 따라, test_command.py에 아래의 test code 추가하였습니다.
- read 함수 test code 추가
- lba 관련 validation test code 추가
> VirtualSSD Read 함수 Refactoring

- virtual_ssd_pkg/command.py
- virtual_ssd_pkg/ssd.py
- virtual_ssd_pkg/test_command.py
ssd write 기능을 변형된 class 구조에 맞게 TDD를 병행하며 refactoring 하였습니다.
기존 VirtualSSD class에서 관리하던 형태를 command class에서 관리하게 되어
기존 class의 불필요한 부분은 제거하고, 신규 class에서 새로 구현하였습니다.
> ssd write refactoring

- virtual_ssd_pkg/test_virtual_ssd.py
- ssd.py cli interface 및 read 관련 test code 추가하였습니다.
> [feature] ssd.py 구조 변경에 따른 test code 수정 및 read 관련 test 추가 하였습니다.

- shell_pkg/command.py
- shell_pkg/shell.py
- shell_pkg/test_shell.py
- shell.py에서 WriteCommand를 생성 및 execute하는 로직 추가
- 리팩토링 및 테스트 코드 추가
> [Shell Write] WriteCommand 생성 로직 추가 

- virtual_ssd_pkg/command.py
- virtual_ssd_pkg/test_virtual_ssd.py
class ssd 변경에 따른 unit test 진행입니다.
read와 동일한 방식으로 write 함수 test 진행하였습니다.
추가적으로 오류가 발생하였던 import error 수정하였습니다.
> class ssd 변경에 따른 unit test 진행

- shell_pkg/command.py
- shell_pkg/shell.py
- shell_pkg/test_shell.py
- WriteCommand 초기화 변수 수정(args 통째로)
- args 길이 검증 추가
- WriteCommand 클래스 초기화 테스트 코드 추가
> [Shell write] WriteCommand 초기화 변수 수정

- shell_pkg/command.py
- shell_pkg/shell.py
- shell_pkg/test_shell.py
- Read 함수 명령어에 대한 유효성 체크 동작이 추가되면서
- 생성자에 명령어 전체를 전달해주도록 변경
- 생성자 변경에 따른 unittest code 수정
- FullRead 함수의 Read 함수 생성자 호출 부분 수정
> [Feature] Read 함수 오류 수정

- shell_pkg/shell.py
> [feature] 예외 출력을 위한 try문 추가

- virtual_ssd_pkg/ssd.py
VirtualSSD class가 호출될 때, 모든 데이터가 flush 되는 오류 수정입니다.
> VirtualSSD class가 호출될 때, 모든 데이터가 flush 되는 오류 수정

- shell_pkg/test_shell.py
> [refactoring] Test 코드 값 변수화

- shell_pkg/command.py
- shell_pkg/shell.py
명령어 입력시 의도하지 않은 input 값이 들어올때 invalid cmd 처리하도록 수정
> [Feature] fullread, testapp1 명령어 처리 동작 수정

- shell_pkg/command.py
- shell_pkg/constants.py
- shell_pkg/test_shell.py
- virtual_ssd_pkg/command.py
- virtual_ssd_pkg/constants.py
MIN_LBA = 0
MAX_LBA = 99 
추가했습니다
> LBA constants 화

- shell_pkg/command.py
- shell_pkg/shell.py
- 미사용 변수 삭제: Shell의 file_path 변수
- INVALID COMMAND 변수 적용
> [refactoring] shell 및 command 수정

- virtual_ssd_pkg/command.py
- virtual_ssd_pkg/constants.py
- virtual_ssd_pkg/ssd.py
- virtual_ssd_pkg/test_virtual_ssd.py
erase 기능 구현 내용입니다.
* 사용 형태 : E [LBA] [SIZE]
* LBA : 0~99의 정수
* SIZE : 1~10의 정수
* LBA + SIZE 가 99보다 클 경우, erase LBA범위는 [ [LBA] , 99]로 설정
* constant 파일 이용
> VirtualSSD Erase 기능 구현

- shell_pkg/commands/testapp1_command.py
- shell_pkg/commands/testapp2_command.py
> [bugfix] testapp evaluation result bugfix

- shell_pkg/shell.py
runner 동작수정 하면서 shell내에서 exception 발생 시 계속 동작하지 않고 종료되어서 다시 수정하여 원복하였습니다
> [bugfix] shell내에서 Exception 발생시 종료 수정

- virtual_ssd_pkg/buffer_manager.py
- 조건문 파라미터 오류 수정(bugfix)
- write 및 erase 조건문 리팩토링
- 함수명 오타 수정(lab...)
> [bugfix/refactoring] buffer_manager의 read command 조건문 수정
